### ISSUE TITLE
Lots of undefined errors

### ISSUE THREAD

**Issue by windowshopr** [mlnoga/go-imap-backup#6]
```
go get golang.org/x/sys golang.org/x/term golang.org/x/text github.com/emersion/go-imap github.com/emersion/go-imap github.com/emersion/go-sasl github.com/schollz/progressbar
```
```
go: downloading golang.org/x/text v0.6.0
go: downloading github.com/emersion/go-sasl v0.0.0-20220912192320-0145f2c60ead
go: upgraded github.com/emersion/go-sasl v0.0.0-20200509203442-7bfe0ed36a21 => v0.0.0-20220912192320-0145f2c60ead
go: added github.com/schollz/progressbar v1.0.0
go: upgraded golang.org/x/text v0.3.7 => v0.6.0
```

```
go run main.go query -s "imap.gmail.com" -p 993 -u "xxx@gmail.com" -P "xxx"
```
```
# command-line-arguments
.\main.go:82:3: undefined: cmdLocalQuery
.\main.go:118:22: undefined: ListFolders
.\main.go:128:17: undefined: intersect
.\main.go:134:3: undefined: cmdQuery
.\main.go:137:3: undefined: cmdBackup
.\main.go:140:3: undefined: cmdRestore
.\main.go:143:3: undefined: cmdDelete
```

**Comment by windowshopr** [comment]
This is on `go version go1.19 windows/amd64`

**Comment by mlnoga** [comment]
Thank you for your feedback. This error happens because you are calling `go build` with just one file argument, `main.go`, so it doesn't see the functions provided in other files in this directory.  Also, with the standard flags package, you need to provide flags before the command. So if you'd like to use `go build`, this should work:

`go run . -s "imap.gmail.com" -u "xxx@gmail.com" query`

Recommended usage remains `go build`, followed by `./go-imap-backup [flags] command`. I have updated README.md to document the ordering of the flags and the command. Hope this helps.
